version: '3'
services:
  nsiaf-backend:
    build:
      context: ../../
      dockerfile: docker/almacenes/backend/Dockerfile
    image: nsiaf:1.0.0
    container_name: nsiaf-backend
    ports:
      - "8888:3000"
    depends_on:
      - nsiaf-db
    env_file: .env
    restart: always
  nsiaf-ufv:
    build:
      context: ../../
      dockerfile: docker/almacenes/ufv/Dockerfile
    image: nsiaf-ufv:1.0.0
    container_name: nsiaf-ufv
    depends_on:
      - nsiaf-db
    env_file: .env
    restart: always
  nsiaf-db:
    image: mysql:5.5
    container_name: nsiaf-db
    ports:
      - "3306:3306"
    volumes:
      - nsiaf-db:/var/lib/mysql
    env_file: .env
    restart: always
volumes:
  nsiaf-db:
